### ISSUE TITLE
New species: Vampire Bat

### ISSUE THREAD

**Issue by MeliodasDL** [MaksiRose/paw-and-paper#687]
### What is the name of the species?

Vampire Bat

### What diet does the species have?

carnivore

### What habitat does the species live in?

warm (shrubland, savanna, desert)

### What prey does this species eat or hunt?

Moths, Rodents, Mice, Small animals, blood, (But occasionally fruit).

### What predators eat or hunt this species?

Humans

### Sources

1. [NatGeo](https://kids.nationalgeographic.com/animals/mammals/facts/vampire-bat) 
2. [SeaWorld](https://seaworld.org/animals/facts/mammals/common-vampire-bat/) 
3. [Wikipedia](https://en.m.wikipedia.org/wiki/Vampire_bat)

**Comment by MaksiRose** [comment]
@KhanFulton I am not sure how to add this animal to the database due to its unique features.
Each animal encounters specific animals based on its prey and predators, which it is able to kill. There are three biomes, and in the first biome it meets around three animals it preys on, in the third it is around three animals that hunt it, and in the middle one there is a mixture of both or animals that are equally strong.

Humans are not counted here since all animals that it can meet must also be animals that the user can play as. Since vampire bats specifically *only* drink blood and do so from lifestock (not killing them in the process), it's hard to say which animals it would win and lose fights against.

The following is the animals I decided on. If you believe other animals should be chosen, please contact me on discord: maksi#8022
<img width="384" alt="image" src="https://user-images.githubusercontent.com/96802571/210576584-a53232a5-1ed4-41e7-b101-a498d7702c07.png">

**Comment by MeliodasDL** [comment]
Bats in general, then?

**Comment by MaksiRose** [comment]
@KhanFulton I think just "bats" is too vague. I already implemented this now (so you can select that species the next time you use the bot!), but if you are not happy with the kinds of opponents you are getting you can let me know which ones I should replace them with.

**Comment by MeliodasDL** [comment]
Ok
